## Examples: https://github.com/rabbitmq/diy-kubernetes-examples/blob/master/kind/base/configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  enabled_plugins: |
    [rabbitmq_federation,rabbitmq_management,rabbitmq_peer_discovery_k8s].
  rabbitmq.conf: |
    ## This is just an example.
    ## This enables remote access for the default user with well known credentials.
    ## Consider deleting the default user and creating a separate user with a set of generated
    ## credentials instead.
    ## Learn more at https://www.rabbitmq.com/access-control.html#loopback-users
    loopback_users.guest = false
    
    listeners.tcp.default = 5672
    
    ## Cluster formation. See https://www.rabbitmq.com/cluster-formation.html to learn more.
    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    
    ## See https://www.rabbitmq.com/ha.html#master-migration-data-locality
    queue_master_locator=min-masters
